name: Deploy to Production 

on:
 push:
  branches: ["main"]

jobs:
  build: 
    name: deploy on ec2
    runs-on: ubuntu-latest
    

    steps:
      - name: get the code
        uses: actions/checkout@v2

      - name: shh into the machine
        run: |
          echo "${{ secrets.PAYMENT_BACKEND_SHH}}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@13.201.91.187 "whoami && uptime"
          cd backend
          git pull origin main
          npm install
          npm run build
          source ~/.bashrc
          pm2 restart ./dist/index.js
      
  

          



        
        