name: Deploy to Production 

on:
 push:
  branches: ["main"]

jobs:
  build: 
    name: deploy on ec2
    runs-on: ubuntu-latest
    

    steps:
      - name: get the code
        uses: actions/checkout@v2

      - name: shh into the machine
        uses: appleboy/ssh-action@v1
        with:
          host: 13.201.91.187
          username: ubuntu
          password: ${{ secrets.PAYMENT_BACKEND_SHH }}
          port: 22
          script: whoami


        
        