name: deploy on ec2
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - run: |
          echo "${{secrets.PAYMENT_BACKEND_SHH}}" &> ~/shh_key
          echo ~/shh_key
        
        